# MCP SandboxRunner Server Configuration

# Server configuration
server:
  name: "SandboxRunner MCP Server"
  version: "1.0.0"
  protocol: "stdio"  # stdio or http
  address: "localhost"
  port: 3000
  read_timeout: "30s"
  write_timeout: "30s"
  enable_http: false

# Sandbox management configuration
sandbox:
  workspace_dir: "/tmp/sandboxrunner/workspaces"
  database_path: "/tmp/sandboxrunner/sandboxes.db"
  default_image: "ubuntu:22.04"
  default_resources:
    cpu_limit: "1.0"
    memory_limit: "1G"
    disk_limit: "10G"
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    DEBIAN_FRONTEND: "noninteractive"
  network_mode: "none"  # none, bridge, host
  enable_logging: true
  cleanup_interval: "5m"
  max_sandboxes: 10

# Logging configuration
logging:
  level: "info"  # debug, info, warn, error
  format: "json"  # json, text, console
  output_file: ""  # empty for stdout
  max_size: 100    # MB
  max_backups: 3
  max_age: 28      # days
  compress: true

# Tools configuration
tools:
  enabled_tools:
    - "create_sandbox"
    - "list_sandboxes" 
    - "terminate_sandbox"
    - "exec_command"
    - "run_code"
    - "upload_file"
    - "download_file"
    - "list_files"
    - "read_file"
    - "write_file"
  disabled_tools: []
  default_timeout: "30s"
  max_output_size: 1048576  # 1MB
  custom_tools: {}
  validation_level: "strict"  # strict, moderate, permissive

# Resources configuration
resources:
  max_file_size: 10485760  # 10MB
  max_files: 1000
  temp_dir: "/tmp/sandboxrunner/temp"
  cache_dir: "/tmp/sandboxrunner/cache"
  cleanup_on_exit: true