# Performance Testing Configuration
# =================================

# Output settings
output_dir: /tmp/sandboxrunner-perf
temp_dir: /tmp
log_level: info
test_timeout: 30m
container_image: ubuntu:22.04
network_mode: none

# Default resource limits
default_cpu_limit: "0.5"
default_memory_limit: 128m
default_disk_limit: 1g

# Performance targets (Phase 5.1.3 requirements)
targets:
  container_startup_ms: 500      # Container startup < 500ms
  command_overhead_ms: 100       # Command execution overhead < 100ms
  memory_per_sandbox_mb: 50.0    # Memory usage < 50MB per sandbox
  max_concurrent_sandboxes: 100  # Support 100+ concurrent sandboxes
  api_response_p99_ms: 200       # API response time p99 < 200ms
  throughput_rps: 100.0          # Throughput target > 100 RPS
  error_rate_percent: 5.0        # Error rate < 5%

# Benchmark test configuration
benchmarks:
  enabled: true
  iterations: 100
  warmup_iterations: 10
  test_container_lifecycle: true
  test_tool_execution: true
  test_language_execution: true
  test_file_operations: true
  test_concurrency: true
  max_concurrency: 16  # 4 cores * 4
  benchmark_timeout: 10m

# Load test configuration
load_tests:
  enabled: true
  sustained_load: true
  burst_traffic: true
  memory_pressure: true
  resource_exhaustion: true
  long_running_ops: true
  
  # Sustained load settings
  sustained_duration: 2m
  sustained_concurrency: 50
  
  # Burst traffic settings
  burst_size: 100
  burst_duration: 10s
  burst_rest_period: 10s
  num_bursts: 5
  
  # Memory pressure settings
  memory_test_sandboxes: 100
  memory_per_sandbox: 128m
  
  # Long-running operation settings
  long_running_duration: 5m

# Memory testing configuration
memory:
  enabled: true
  leak_detection: true
  goroutine_leak_detection: true
  concurrent_memory_test: true
  large_data_handling: true
  
  # Memory monitoring settings
  profile_interval: 500ms
  gc_before_test: true
  
  # Test data sizes
  small_data_size_kb: 1
  medium_data_size_kb: 10
  large_data_size_mb: 1

# Profiling configuration
profiling:
  enabled: false  # Enable explicitly when needed
  cpu_profile: true
  memory_profile: true
  block_profile: true
  mutex_profile: true
  goroutine_profile: true
  trace: true
  
  profile_duration: 2m
  output_dir: /tmp/sandboxrunner-profiles
  auto_analysis: false

# Environment-specific overrides
# Uncomment and modify for different environments

# CI/CD environment (faster, limited resources)
# ci:
#   benchmarks:
#     iterations: 10
#     max_concurrency: 4
#   load_tests:
#     sustained_duration: 30s
#     sustained_concurrency: 10
#     burst_size: 20
#   targets:
#     max_concurrent_sandboxes: 20

# Development environment (comprehensive testing)
# dev:
#   benchmarks:
#     iterations: 500
#     max_concurrency: 32
#   load_tests:
#     sustained_duration: 10m
#     sustained_concurrency: 100
#   profiling:
#     enabled: true

# Production validation (strict performance requirements)
# prod:
#   targets:
#     container_startup_ms: 250
#     command_overhead_ms: 50
#     memory_per_sandbox_mb: 25.0
#     api_response_p99_ms: 100
#     error_rate_percent: 1.0